package com.springvuegradle.team200.repository;

import com.springvuegradle.team200.model.ActivityType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;
import java.util.Optional;

@RepositoryRestResource
public interface ActivityTypesRepository extends JpaRepository<ActivityType, Long> {

    @Query("SELECT a FROM ActivityType a WHERE a.type = ?1")
    ActivityType getActivityTypesFromName(String name);

    @Query(value = "SELECT type FROM ActivityType")
    List<String> getAllActivityTypes();

    // Query is automatically generated by Spring
    Optional<ActivityType> findByType(String activityType);
}
