package com.springvuegradle.team200.repository;

import com.springvuegradle.team200.model.PassportCountry;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;

@RepositoryRestResource
public interface UserPassportRepository extends JpaRepository<PassportCountry, Long> {

    @Query(value = "SELECT p FROM PassportCountry p WHERE p.name = ?1")
    List<PassportCountry> getPassportCountriesByName(String country);

    @Query(value = "SELECT p FROM PassportCountry p WHERE p.code = ?1")
    PassportCountry getPassportCountryByCode(String code);

    // Query is automatically generated by Spring
    PassportCountry findByName(String name);
}
